name: Fay Frontend Build

concurrency:
  group: dev
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: sample

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: codygo

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: Build app
        run: pnpm run build
