name: Build and Deploy

concurrency:
  group: dev
  cancel-in-progress: true

on:
  push:
  # branches:
  #   - main
  # pull_request:
  #   types:
  #     - ready_for_review

  #   paths:
  #     - "NO_SUCH_PATH_apps/**"
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  AWS_REGION: eu-central-1

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: codygo
